use_frameworks!

target 'RPTMultiSelection_Example' do
  pod 'RPTMultiSelection', :path => '../'

  target 'RPTMultiSelection_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
